Anahaw/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

Bookface/urls.py
# yourprojectname/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("posts/", include("posts.urls")),  
]

posts/urls.py
# posts/urls.py
from django.urls import path
from .views import post_list, news_feed

urlpatterns = [
    path('posts/', post_list, name='post_list'),
    path('news-feed/', news_feed, name='news_feed'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('todolist.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bookface/models.py
# models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    content = models.TextField()
    image = models.ImageField(upload_to='post_images/', null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author.username} - {self.created_at}"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True)

    def __str__(self):
        return self.user.username

class Message(models.Model):
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='received_messages', on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True)

bookface/forms.py
# bookface/forms.py
from django import forms
from .models import Post, UserProfile, Message

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'image']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control-no-border'}),
        }

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_picture']
        
        
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['content']

bookface/views.py
# bookface/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from .models import Post, UserProfile, Message
from .forms import PostForm, UserProfileForm, MessageForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.db import models
from django.http import JsonResponse
from django.db.models import Q
from django.views.decorators.http import require_POST


def register_view(request):
    if request.user.is_authenticated:
        return redirect("home")  # Redirect to home if user is already logged in

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("home")  # Change 'home' to the name of your home view
    else:
        form = UserCreationForm()
    return render(request, "register.html", {"form": form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect("home")  # Redirect to home if user is already logged in

    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("home")  # Change 'home' to the name of your home view
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})


def logout_view(request):
    logout(request)
    return redirect("login")  # Change 'login' to the name of your login view


@login_required(login_url=reverse_lazy("login"))
def home(request):
    posts = Post.objects.all().order_by("-created_at")
    user = request.user

    # Get a list of users with whom the current user has chatted
    chat_list = (
        Message.objects.filter(Q(sender=user) | Q(receiver=user))
        .order_by("-timestamp")
        .values("sender", "receiver")
        .distinct()
    )

    return render(request, "home.html", {"posts": posts, "chat_list": chat_list})


@login_required(login_url=reverse_lazy("login"))
def create_post(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("home")
    else:
        form = PostForm()
    return render(request, "create_post.html", {"form": form})


def post_detail(request, post_id):
    post = Post.objects.get(pk=post_id)
    return render(request, "post_detail.html", {"post": post})


def view_profile(request, username):
    user = get_object_or_404(User, username=username)
    profile = UserProfile.objects.get_or_create(user=user)[0]

    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
    else:
        form = UserProfileForm(instance=profile)

    return render(request, "profile.html", {"user": user, "form": form})

@login_required(login_url=reverse_lazy("login"))
def chat_room(request, username):
    other_user = get_object_or_404(User, username=username)
    messages = Message.objects.filter(
        (
            models.Q(sender=request.user, receiver=other_user)
            | models.Q(sender=other_user, receiver=request.user)
        )
    ).order_by("timestamp")

    # Get a list of users with whom the current user has chatted
    chat_list = get_chat_list(request.user)

    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = request.user
            message.receiver = other_user
            message.save()
            return redirect("chat_room", username=username)
    else:
        form = MessageForm()

    context = {
        "other_user": other_user,
        "messages": messages,
        "form": form,
        "chat_list": chat_list,
    }
    return render(request, "chat_room.html", context)

@require_POST
@login_required(login_url=reverse_lazy("login"))
def send_message(request, username):
    other_user = get_object_or_404(User, username=username)
    content = request.POST.get("content", "")

    if content:
        message = Message.objects.create(
            sender=request.user, receiver=other_user, content=content
        )
        return JsonResponse({"success": True, "message_id": message.id})
    else:
        return JsonResponse({"success": False, "error": "Content cannot be empty"})

def get_chat_list(user):
    # Get a list of users with whom the current user has chatted
    chat_list = (
        Message.objects.filter(Q(sender=user) | Q(receiver=user))
        .order_by("-timestamp")
        .values("sender", "receiver")
        .distinct()
    )

    return chat_list

bookface/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Bookface</title>
    <!-- Add Bootstrap CSS link -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
      integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
    <style>
    .navbar-elevated {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
      }
    </style>
  </head>
  
  <body style="background-color: #F0F2F5;">
    <nav class="navbar navbar-expand-lg navbar-light navbar-elevated sticky-md-top bg-white">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"
          ><img
            src="{% static 'bookface/images/bookface_logo.svg' %}"  
            alt="Image 1"
            height="45"
            style="margin-top: -15px; margin-bottom: -15px;"
        /></a>
        <div class="col-md-3">
          <input
            class="form-control rounded-pill"
            type="search"
            placeholder="Search Bookface"
            id="example-search-input"
          />
        </div>
        </button>
        <div class="collapse navbar-collapse col-md-6 justify-content-md-around" id="navbarNav">
          <ul class="nav nav-pills nav-fill">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <!-- <a class="nav-link active" aria-current="page" href="{% url 'home' %}"><i class="fas fa-home"></i></a> -->
            </li>
            {% endif %}
          </ul>
        </div>  
        <div class="col-md-2 d-flex justify-content-md-end">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'create_post' %}"> <button type="button" class="btn text-black bg-secondary-subtle rounded-5 me-1" style="color: black;"><i class="fas fa-plus"></i></button> </a>
            

            <div class="dropdown">
                <button type="button" class="btn text-black bg-secondary-subtle rounded-5 me-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-comment"></i></button>
                <ul class="dropdown-menu dropdown-menu-end">
                    {% for chat in chat_list %}<li>
                        {% if chat.sender.username %}
                        <a class="dropdown-item" href="{% url 'chat_room' username=chat.sender.username %}">{{ chat.sender.username }}</a>
                      {% elif chat.receiver.username %}
                        <a class="dropdown-item" href="{% url 'chat_room' username=chat.receiver.username %}">{{ chat.receiver.username }}</a>
                      {% else %}
                        <p>Invalid username</p>
                      {% endif %}
                    </li>
                    
                    {% endfor %}    
                </ul>
            </div>

                  <div class="dropdown">
            <button type="button" class="btn text-black bg-secondary-subtle rounded-5 me-1"  data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-bell"></i></button> 
                    <ul class="dropdown-menu dropdown-menu-end">
                      <li><button class="dropdown-item" type="button">Notifs</button></li>
                      <li><button class="dropdown-item" type="button">Another action</button></li>
                      <li><button class="dropdown-item" type="button">Something else here</button></li>
                    </ul>
                  </div>

                  <div class="dropdown">
            <button type="button" class="btn text-black bg-secondary-subtle rounded-5 me-2" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user-circle"></i></button>

                            <ul class="dropdown-menu dropdown-menu-end">
<a class="dropdown-item" href="{% url 'view_profile' username=user.username %}">View Profile</a>

                                <a class="dropdown-item" href="#">Settings</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                            </ul>
                          </div>
           
                {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
        </div>

      </div>
    </nav>

    <div class="mt-3 bg-light">{% block content %} {% endblock %}</div>

    <!-- Add Bootstrap JS and Popper.js (optional, for Bootstrap components that require it) -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
      integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

bookface/templates/chat_room.html
<!-- chat_room.html -->
{% extends 'base.html' %} {% block content %}
<style>
  .profile-picture {
    width: 50px;
    height: 50px;
    border-radius: 50%;
    margin-right: 10px;
    object-fit: cover;
  }

  .chat-container {
    display: flex;
    flex-direction: row;
    height: 100vh; /* Set the container height to 100% of the viewport height */
  }

  .col-4 {
    /* Add styling for the chatlist column as needed */
    background-color: #ffffff;
  }

  .col-6 {
    /* Adjust styling for the chat messages and form column */
    background-color: #f0f2f5;
    display: flex;
    height: 550px;

    flex-direction: column;
  }

  .chat-messages {
    /* Set flex-grow to 1 to make it take up remaining space */
    flex-grow: 1;
    display: flex;
    flex-direction: column;
    align-items: flex-end; /* Right-align the messages */
    overflow-y: auto; /* Add a vertical scrollbar if needed */
  }

  .message-bubble {
    padding: 10px;
    margin: 5px;
    border-radius: 10px;
    max-width: 70%;
  }

  .own-message {
    background-color: #3498db;
    color: #fff;
    align-self: flex-end;
  }

  .other-message {
    background-color: #ffffff;
    color: #000;
    align-self: flex-start; /* Left-align the other user's messages */
  }

  .form-container {
    /* Add styling for the form container */
    background-color: #f0f2f5;
    padding: 10px;
  }
</style>
<div class="chat-container" style="background-color: #f0f2f5">
  <div class="col-4" style="background-color: #f0f2f5">
    <ul>
      {% for chat in chat_list %}
      <li>
        {% if chat.sender == request.user %} 
        {{ chat.receiver.username }} 
       {%else %}
         {{chat.sender}} 
         {% endif %}
      </li>
      {% endfor %}
    </ul>
  </div>
  <div class="col-6">
    <div
      class="list-group-item d-flex align-items-center pb-3 bg-dark-subtle p-3"
      style="
        background-color: #f0f2f5;
        border-bottom-right-radius: 20%;
        border-bottom-left-radius: 20%;
      "
    >
      <img
        src="{{ other_user.userprofile.profile_picture.url }}"
        alt="Profile Picture"
        class="profile-picture"
      />
      <h2>{{ other_user.username }}</h2>
    </div>

    <div id="chat-messages" class="chat-messages">
      {% for message in messages %}
      <div
        class="message-bubble {% if message.sender == user %}own-message{% else %}other-message{% endif %}"
      >
        {{ message.content }}
      </div>
      {% endfor %}
    </div>

    <div class="form-container">
      <form
        method="post"
        class="row justify-content-between"
        action="{% url 'chat_room' username=other_user.username %}"
        id="message-form"
      >
        {% csrf_token %}
        <div class="row col-10 text-center">{{ form.content }}</div>
        <div class="col-2 text-end">
          <button type="submit">Send</button>
        </div>
      </form>
    </div>
  </div>
  <div class="col-2" style="background-color: #f0f2f5"></div>
</div>

<script>
  // Add this script to automatically scroll to the bottom of the chat messages
  var chatMessages = document.getElementById("chat-messages");
  chatMessages.scrollTop = chatMessages.scrollHeight;

  // Prevent scrolling of the entire page when scrolling within the chat messages
  document.body.style.overflow = "hidden";
  chatMessages.addEventListener("scroll", function () {
    if (
      chatMessages.scrollTop + chatMessages.clientHeight >=
      chatMessages.scrollHeight
    ) {
      // Enable scrolling if at the bottom of the chat messages
      document.body.style.overflow = "hidden";
    } else {
      // Disable scrolling if not at the bottom
      document.body.style.overflow = "hidden";
    }
  });
</script>
{% endblock %}

bookface/templates/create_post.html
<!-- create_post.html -->
{% extends 'base.html' %}
{% block content %}
<style>
  /* Add a custom style for the textarea to remove the border */
  textarea.no-border {
    border: none;
    resize: none; /* Disable textarea resizing if needed */
  }
</style>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title mb-4">Create Post</h2>
          <b>{{ user }}</b>
          <form method="post" action="{% url 'create_post' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row justify-content-center">
              <div class="col-9 mb-3">
                {{ form.content }}
              </div>
            </div>
            <div class="row justify-content-center">
              <div class="col-9 mb-3">
                {{ form.image }}
              </div>
            </div>
            <div class="row justify-content-center">
              <button type="submit" class="btn btn-primary btn-block">
                Post
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

bookface/templates/home.html
<!-- bookface/templates/home.html -->
{% extends 'base.html' %} {% block content %}
{%load static%}
<style>
  /* Add custom CSS to make the column scrollable */
  .scrollable-column {
    max-height: 80vh; /* Set a maximum height for the scrollable area */
    overflow-y: auto; /* Enable vertical scrolling */
  }

  /* Add custom CSS to style the profile picture */
  .profile-picture {
    width: 50px; /* Adjust the width as needed */
    height: 50px; /* Adjust the height as needed */
    border-radius: 50%;
    margin-right: 10px;
    object-fit: cover;
  }
  .side-profile-picture {
    width: 30px; /* Adjust the width as needed */
    height: 30px; /* Adjust the height as needed */
    border-radius: 50%;
    margin-right: 10px;
    object-fit: cover;
  }
  .advertisement {
    width: 150px; /* Adjust the width as needed */
    height: 150px; /* Adjust the height as needed */
    margin-left: 10px;
    object-fit: cover;
    border-radius: 10%;
  }

  /* Add custom CSS to prevent stretching of images */
</style>

<div class="row" style="background-color: #f0f2f5">
  <div class="col-md-3">   
    <ul class="list-group list-group-flush " >
      <a href="{% url 'view_profile' username=user.username %}" ">
    <li class="list-group-item d-flex align-items-center pb-3" style="background-color: #f0f2f5">
      {% if user.userprofile.profile_picture %}
        <img
          src="{{ user.userprofile.profile_picture.url }}"
          alt="Profile Picture"
          class="side-profile-picture"
        />
      {% else %}
        <img
          src="profile_pics/default_profile.jpg"
          alt="Profile Picture"
          class="profile-picture"
        />
      {% endif %}
      <div class="ps-1">
      <a href="{% url 'view_profile' username=user.username %}" style="text-decoration: none; color: rgb(26, 25, 25);">
        <h6 class="card-title">
          {{ user.username }}
        </h6>
        </a></div>
      </a>

    </li>
    <li class="list-group-item my-2 pb-3" style="background-color: #f0f2f5">
     <i class="fa fa-user-group pe-3 ms-1 text-primary" ></i> Friends
    </li>
    <li class="list-group-item my-2 pb-3" style="background-color: #f0f2f5">
      <i class="fa fa-list-check pe-3 ms-1 text-primary" ></i> Todolist
     </li>
     <li class="list-group-item my-2 pb-3" style="background-color: #f0f2f5">
      <i class="fa fa-message pe-3 ms-1 text-primary" ></i> Messages
     </li>
  </ul>
</div>
  <div class="col-md-6 justify-content-md-start scrollable-column">
    <div class="mb-5">
      <img
      src="{% static 'bookface/images/bookface.png' %}"  
      alt="Image 1"
      height="50"
      style="margin-top: -15px; margin-bottom: -15px;"
  />
    </div>
    {% for post in posts %}
    <div class="card mb-4" style="min-height: 150px;">
      <div class="card-header d-flex align-items-center bg-dark-subtle">
        {% if post.author.userprofile.profile_picture %}
        <a href="{% url 'view_profile' username=post.author.username %}" ">
          <img
            src="{{ post.author.userprofile.profile_picture.url }}"
            alt="Profile Picture"
            class="profile-picture"
          />
        </a>
        {% else %}
        <a href="{% url 'view_profile' username=post.author.username %}">
          <img
            src="profile_pics/default_profile.jpg"
            alt="Profile Picture"
            class="profile-picture"
          />
        </a>
        {% endif %}
        <div>
          <a href="{% url 'view_profile' username=post.author.username %}" style="text-decoration: none; color: rgb(26, 25, 25);">
            <h6 class="card-title">
              <b>{{ post.author.username }}</b>
            </h6>
          </a>
          <h6 class="card-subtitle mb-2 text-body-secondary">
            <small>{{ post.created_at}}</small>
          </h6>
        </div>
      </div>
      <div class="card-body">
        <p class="card-text">{{ post.content }}</p>
        {% if post.image %}
        <img
          src="{{ post.image.url }}"
          alt="Post Image"
          class="img-fluid img-fit"
        />
        {% endif %}
      </div>
      <div class="card-footer">
        <a href="#" class="card-link">Like</a>
        <a href="#" class="card-link">Comment</a>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="col-md-3">
    <div class="mb-3">
    <b class="text-light-emphasis">Advertisement</b>
    </div>
    <div class="d-flex align-items-center">
    <img
    src="{% static 'bookface/images/shawarma_Rice.jpg' %}"  
    alt="AD Shawarma Rice yum yum"
    class="advertisement"
  />
  <p class="ms-2 d-block">Shawarma Rice </p>
  
  <!-- <a href="shopee.ph"><small>shopee.ph</small></a> -->
</div>
<div class="d-flex align-items-center mt-2">
  <img
  src="{% static 'bookface/images/mixnmatch.jpeg' %}"  
  alt="AD mixnmatch"
  class="advertisement"
/>
<p class="ms-2 d-block">Mix and Match </p>

<!-- <a href="shopee.ph"><small>shopee.ph</small></a> -->
</div>
  </div>
</div>

<div class="dropdown">
  <button type="button" class="btn text-black bg-secondary-subtle rounded-5 me-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-comment"></i></button>
  <ul class="dropdown-menu dropdown-menu-end">
      {% for chat in chat_list %}
      <li>
        {% if chat.sender.username %}
            <a class="dropdown-item" href="{% url 'chat_room' username=chat.sender.username %}">{{ chat.sender.username }}</a>
        {% else %}
            <p>Invalid username</p>
        {% endif %}
    </li>
    
      {% endfor %}
  </ul>
</div>
{% endblock %}

bookface/templates/login.html
<!-- bookface/templates/login.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post" action="{% url 'login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

bookface/templates/post_detail.html
<!-- bookface/templates/post_detail.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Post Detail</h2>
  <p>{{ post.content }} - {{ post.author.username }} ({{ post.created_at }})</p>
{% endblock %}

bookface/templates/profile.html
<!-- bookface/templates/profile.html -->
{% extends 'base.html' %} {% block content %}
<div
  style="display: flex; align-items: center; background-color: #f0f2f5"
  class=""
>
  <div class="col-2">eme</div>
  <div class="col-8 d-flex align-items-center">
    <!-- Added d-flex and align-items-center -->
    <div style="position: relative">
      <div
        style="
          width: 100px;
          height: 100px;
          overflow: hidden;
          border-radius: 50%;
          margin-right: 10px;
        "
      >
        {% if user.userprofile.profile_picture %}
        <img
          src="{{ user.userprofile.profile_picture.url }}"
          alt="Profile Picture"
          class="img-fluid"
          style="
            width: 100%;
            height: 100%;
            object-fit: cover;
            border-radius: 50%;
          "
        />
        {% else %}
        <img
          src="/profile_pics/default_profile.jpg"
          alt="Default Profile Picture"
          class="img-fluid"
          style="
            width: 100%;
            height: 100%;
            object-fit: cover;
            border-radius: 50%;
          "
        />
        {% endif %}
      </div>
      <!-- Add a button to toggle the modal -->
      <button
        style="position: absolute; bottom: 5px; right: 15px"
        class="rounded-5 flat"
        data-bs-toggle="modal"
        data-bs-target="#editProfileModal"
      >
        <i class="fas fa-edit"></i>
      </button>
    </div>
    <h2>{{ user.username }}</h2>
  </div>
  <div class="col-2">eme</div>
</div>

<!-- Add a modal for the profile picture edit form -->
<div
  class="modal fade"
  id="editProfileModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="editProfileModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editProfileModalLabel">
          Edit Profile Picture
        </h5>
        <button
          type="button"
          class="close"
          data-bs-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <!-- Your profile picture edit form goes here -->
        <form method="post" enctype="multipart/form-data" class="text-center">
          {% csrf_token %}
          <div class="form-group text-center">
            <label for="id_profile_picture"><b>Profile Picture</b></label>
            <div class="circle-preview">
              <input
                type="file"
                name="profile_picture"
                accept="image/*"
                class="form-control"
                id="id_profile_picture"
                style="display: none"
                onchange="previewImage(this)"
              />
              <label for="id_profile_picture" class="choose-image-label"
                >Choose Image</label
              >
              <img id="preview" class="circle-image" />
            </div>
          </div>
          <button class="btn btn-primary" type="submit">Save</button>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Add this to your body section or where you include scripts -->
<!-- Add this to your body section or where you include scripts -->
<style>
  .circle-preview {
    position: relative;
    width: 250px;
    height: 250px;
    margin: 0 auto;
    overflow: hidden;
    border-radius: 50%;
    margin-bottom: 20px;
    margin-top: 20px;
  }

  .circle-image {
    width: 100%;
    height: 100%;
    /* object-fit: cover; */
    border-radius: 50%;
    border: 2px solid black; /* Add border styles here */
  }

  .choose-image-label {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    cursor: pointer;
  }
</style>

<script>
  function previewImage(input) {
    var preview = document.getElementById("preview");
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      reader.onload = function (e) {
        preview.src = e.target.result;
      };
      reader.readAsDataURL(input.files[0]);
    }
  }
</script>
{% endblock %}

bookface/templates/register.html
<!-- bookface/templates/register.html -->
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post" action="{% url 'register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
{% endblock %}